// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MinResourcesMod.AddUnaffiliatedResourcesPatch.Prefix(TenCrowns.GameCore.DefaultMapScript,TenCrowns.GameCore.Infos,Mohawk.SystemCore.RandomStruct,System.Collections.Generic.Dictionary{TenCrowns.GameCore.ResourceType,System.Int32},System.Collections.Generic.HashSet{System.Int32})~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:MinResourcesMod.AddUnaffiliatedResourcesPatch.Prefix(TenCrowns.GameCore.DefaultMapScript,TenCrowns.GameCore.Infos,Mohawk.SystemCore.RandomStruct,System.Collections.Generic.Dictionary{TenCrowns.GameCore.ResourceType,System.Int32},System.Collections.Generic.HashSet{System.Int32})~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MinResourcesMod.AddUnaffiliatedResourcesPatch.Prefix(TenCrowns.GameCore.DefaultMapScript,System.Collections.Generic.List{TenCrowns.GameCore.ResourceType})~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MinResourcesMod.AddUnaffiliatedResourcesPatch.Prefix(TenCrowns.GameCore.DefaultMapScript,TenCrowns.GameCore.Infos,Mohawk.SystemCore.RandomStruct,System.Collections.Generic.Dictionary{TenCrowns.GameCore.ResourceType,System.Int32},System.Collections.Generic.HashSet{System.Int32},System.Collections.Generic.Dictionary{System.Int32,System.Int32},System.Collections.Generic.Dictionary{System.Int32,TenCrowns.GameCore.ResourceType})~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~M:MinResourcesMod.AddUnaffiliatedResourcesPatch.Prefix(TenCrowns.GameCore.DefaultMapScript,TenCrowns.GameCore.Infos,Mohawk.SystemCore.RandomStruct,System.Collections.Generic.Dictionary{TenCrowns.GameCore.ResourceType,System.Int32},System.Collections.Generic.HashSet{System.Int32},System.Collections.Generic.Dictionary{System.Int32,System.Int32},System.Collections.Generic.Dictionary{System.Int32,TenCrowns.GameCore.ResourceType})~System.Boolean")]
